export enum StatusChamado {
  ABERTO = 'ABERTO',
  EM_ANALISE = 'EM_ANALISE',
  AGENDADO = 'AGENDADO',
  EM_ATENDIMENTO = 'EM_ATENDIMENTO',
  AGUARDANDO_APROVACAO_ORCAMENTO = 'AGUARDANDO_APROVACAO_ORCAMENTO',
  CONCLUIDO = 'CONCLUIDO',
  CANCELADO = 'CANCELADO'
}

